
MYDIR := $(shell basename `pwd`)
OUT := ../$(MYDIR).Rdata

UTILSDEPS := $(shell ls ../utils/*.R)
LOCALDEPS := $(shell ls ./*.R | grep -v script.R)

$(OUT): script.R $(LOCALDEPS) $(UTILSDEPS) ./Makefile
	Rscript $< $@ 2>&1 | tee $(MYDIR).log

clean:
	rm -fr *.Rdata *.pdf *.jpg *.jpeg *.log Res_* TableS*.csv GLM*.txt NA $(OUT)

#### some .txt are not to be removed
#	rm -f *.Rdata *.txt *.pdf *.log result_*.csv TableS*.csv $(OUT) 

